### ISSUE TITLE
[Public] Frontend Night #23

### ISSUE THREAD

**Issue by KentoMoriwaki** [wantedly/frontend_night#23]
- 資料の準備をがんばらない
- 参加・途中退席は自由
- スキップしない

2018/10/25 19:00~20:00

話したい・聞きたいネタを書いてく ✏️

ハッシュタグ [#frontend_night](https://twitter.com/hashtag/frontend_night?src=hash)

🎉 **外部の人も招待する会** 🎉

**Comment by kdnk** [comment]
pure component の function component 版 の RFC

https://github.com/reactjs/rfcs/blob/gaearon-patch-1/text/0000-pure.md
https://twitter.com/dan_abramov/status/1053179247148306433

**Comment by kdnk** [comment]
## CRA が公式でtsサポートするようになった by babel7

https://github.com/facebook/create-react-app/pull/4837

**Comment by kdnk** [comment]
## CRA が公式でtsサポートするようになった by babel7

https://github.com/facebook/create-react-app/pull/4837

**Comment by stomk** [comment]
## The Intl.RelativeTimeFormat API

「○日前」の I18n をする API が JS のネイティブに入る。Chrome 71 から使えるようになる。

https://developers.google.com/web/updates/2018/10/intl-relativetimeformat

**Comment by stomk** [comment]
## Yahoo が早速 WebAuthn によるログインに対応
https://about.yahoo.co.jp/pr/release/2018/10/231023/a/

**Comment by euglena1215** [comment]
## 大量のテキストを食っても速い Markdown Editor 作った
off-the-main-thread事例
https://mizchi.hatenablog.com/entry/2018/10/23/221446

**Comment by stomk** [comment]
## Firefox 63 リリース
https://www.mozilla.org/en-US/firefox/63.0/releasenotes/
https://hacks.mozilla.org/2018/10/firefox-63-tricks-and-treats/

Custom Elements、Shadow DOM がデフォルトで使えるようになった

**Comment by stomk** [comment]
## React 16.6 リリース
https://reactjs.org/blog/2018/10/23/react-v-16-6.html

- React.memo
- React.lazy: Code-Splitting with Suspense
- static contextType
- static getDerivedStateFromError()

**Comment by kdnk** [comment]
Memoization

**Comment by kdnk** [comment]
https://medium.com/@baphemot/understanding-react-suspense-1c73b4b0b1e6

**Comment by kdnk** [comment]
https://codesandbox.io/s/8nq4w3jj39
