### ISSUE TITLE
[2019/11/07] Frontend Night #63

### ISSUE THREAD

**Issue by chloe463** [wantedly/frontend_night#64]
- 資料の準備をがんばらない
- 参加・途中退席は自由
- スキップしない

話したい・聞きたいネタを書いてく ✏️

ハッシュタグ [#frontend_night](https://twitter.com/hashtag/frontend_night?src=hash)

**Comment by chloe463** [comment]
## TypeScript 3.7

https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/

**Comment by kobayang** [comment]
## Building a Custom React Renderer | Sophie Alpert

https://www.youtube.com/watch?v=CGpMlWVcHok

ReactConf 2019 の発表。
簡単なReactDOMを実装をする。実はすごく簡単にRendererは実装できるんだよ、という話。

---

React には reconciler と host components に分割できる。

reconciler の実装は react-reconciler に書かれている。
renderer を実装したい場合は、 react-reconciler の render API に、callback としてイベントが起きた時の動作をそれぞれ実装する

host components の実装は2通りあって、

- mutation mode
  - createDOM みたいにかく
- persistant mode
  - cloneDOM みたいにかく

それぞれの違いについては正確にはよくわからなかった。persistant mode の方が効率的に renderer を実装できるらしい。ReactDOM は mutation mode で実装されていて、react-native は persistant mode に移行中らしい。

この発表では、 mutation mode について深く掘り下げている。

react-reconciler が 以下の react に関連するロジックを全部処理してくれるので、renderer はそのことを知る必要がない。

<img width="317" alt="Screen Shot 2019-11-07 at 16 37 02" src="https://user-images.githubusercontent.com/12181179/68369122-e5ba8480-017c-11ea-880b-1b273287abfc.png">

一つ発表中の例をとると、createInstance （ 一番最初に呼ばれるAPI）の ReactDOM の実際の実装は

https://github.com/facebook/react/blob/cb09dbe0ab0f42185c4892c045b0c32e04f6b9cb/packages/react-dom/src/client/ReactDOMHostConfig.js

にある。

**Comment by KentoMoriwaki** [comment]
ReactConfの発表を総ざらいしたい。
